name: Sync Fork

on:
  schedule:
    - cron: '15 */6 * * *' # At minute 15 past every 6th hour.
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.5.0
        with:
          owner: michpro
          token: ${{ secrets.GITHUB_TOKEN }}
          base: master
          head: master
          auto_approve: true
          merge_method: merge
